### ISSUE TITLE
[1.10.2] [3.0.3] Crash using a bucket

### ISSUE THREAD

**Issue by Alaberti** [Ferdzz/PlaceableItems#10]
A player on my server had this issue when using a bucket - http://pastebin.com/C8cng4nj

**Comment by Ferdzz** [comment]
Thank you for telling me, could you explain the steps needed to reproduce the crash?

**Comment by Alaberti** [comment]
From the player:
"All that happened was that I had a stack of 8 buckets and was flying with Wings of the Bat over the river in the base. I started clicking to see if I would hit a source block, and crashed at one point. No source blocks seemed to be in the area I was clicking."

The river in our base is a stream from the Streams mod which uses nonstandard water blocks.

**Comment by Ferdzz** [comment]
Alright thank you, I'll investigate this

**Comment by Alaberti** [comment]
Awesome, thank you for the prompt fix!

**Comment by Ferdzz** [comment]
It's a pleasure :)
Please do not hesitate to tell us through issues if you encounter more problems
