### ISSUE TITLE
Option to turn OFF warning for placing enchanted items.

### ISSUE THREAD

**Issue by Barerock** [Ferdzz/PlaceableItems#122]
**Is your feature request related to a problem? Please describe.**
Crouching is an unavoidable gameplay mechanic, but shift+right click is the keybind for placing items. Every time I'm building with my offhand or simply swapping things while crouched I get a constant noise spam from the warning.

**Describe the solution you'd like**
Config or keybind option to change the input or presence of the warning.

**Describe alternatives you've considered**
Not having the mod at all.

**Comment by Ferdzz** [comment]
I'm not sure what you mean by noise spam or warning, but you can change the keybind in the settings

**Comment by Barerock** [comment]
The keybind is not in settings. There's a blink blonk sound that states "enchanted items cannot be placed."

**Comment by Barerock** [comment]
Also there's no config for the mod either using Configured or Forge Config Menus

**Comment by Ferdzz** [comment]
What version are you using?

**Comment by Barerock** [comment]
This absolutely isn't the right mod, my bad. I'm looking for Placeables, ugh. Google with its awful results.
