### ISSUE TITLE
Placeable Items won't load

### ISSUE THREAD

**Issue by xxkillerdragxnxx** [Ferdzz/PlaceableItems#126]
![Capture](https://github.com/user-attachments/assets/e4156cca-1828-4ea0-87c5-6174ebfd35c7)
I've been having this problem whenever I try to load the mod into a game and there isn't any place I can find to resolve the issue.
![Capture 2](https://github.com/user-attachments/assets/198d5fa1-d158-4bdd-abac-649b48fc7ce5)

**Comment by Ferdzz** [comment]
Please resubmit while following the Bug report template
