### ISSUE TITLE
Some textures are not 16x16 and can only support mip level 3

### ISSUE THREAD

**Issue by Claycorp** [Ferdzz/PlaceableItems#23]
https://pastebin.com/zqe77FFi

**Comment by Ferdzz** [comment]
I am aware of the console warning, however I'm not quite sure if it impacts anything. Would you care to explain what mip level 3 is and how it affects the mod?

**Comment by JBrion1995** [comment]
I think it just means that your mod is more pixelated compared to vanilla texture when viewed from afar.

**Comment by Ferdzz** [comment]
Thank you for the report, it has been addressed.

More mipmap issues came up during the recent potion texture changes, but they will be fixed before the next release
