### ISSUE TITLE
Resource pack + mod

### ISSUE THREAD

**Issue by Madis0** [Ferdzz/PlaceableItems#34]
Have you considered making this mod instead a resource pack where all items are swapped with models right away? And for placing them, you could make the item frame model invisible. 

That would make it easier for users to use it in multiplayer and in newer versions of the game. The mod part could be just used to give the placed items special abilities (eatability, bounce effect, etc.).

**Comment by Ferdzz** [comment]
Yes. In fact we have a resource pack coming along, and it is soon to be finished. This resource pack will replace the vanilla items with their respective PI models and will be fully independent from the mod itself.

However, the mod will keep it's current place in the Placeable Items family, making the resource pack a nice addition for people who want a more immersive experience. Hope that answered your questions!
