### ISSUE TITLE
Mod not loading.

### ISSUE THREAD

**Issue by Sunless-Skies** [Ferdzz/PlaceableItems#36]
The mod, Placeable items, refuses to load on my system. I have tried two different versions of forge - 1.12.2 and 1.12, and the error appears to be the same.

The three crash logs are as follows:
[crash-2018-03-12_00.51.39-client.txt](https://github.com/Ferdzz/PlaceableItems/files/1800472/crash-2018-03-12_00.51.39-client.txt)
[crash-2018-03-12_00.40.03-client.txt](https://github.com/Ferdzz/PlaceableItems/files/1800473/crash-2018-03-12_00.40.03-client.txt)
[crash-2018-03-12_00.35.23-client.txt](https://github.com/Ferdzz/PlaceableItems/files/1800474/crash-2018-03-12_00.35.23-client.txt)

Due to lack of available time, I cannot test whether or not it is other mods causing the issue. I will update this post with more information as I find it tomorrow.

**Comment by mchorse** [comment]
@Sunless-Skies you're running 1.12.2 version of PlaceableItems mod on Forge 1.11.2. You need to either download 1.11.2 version of the mod, or install Forge for 1.12.2.

**Comment by mchorse** [comment]
@Ferdzz looks like I still have the permission to the repository (as a collaborator). I don't know whether you remember this, but I think it's best to remove me from collaborators (since I haven't really did any contributions).

**Comment by Ferdzz** [comment]
@mchorse Thank you very much for handling this issue for me! I will remove your collaborator status if you feel like you shouldn't have it, but I truly appreciate your help and interest nonetheless! 

@Sunless-Skies Let us know if you're still having issues installing the mod
