### ISSUE TITLE
3.3 is busted

### ISSUE THREAD

**Issue by NotAVerb** [Ferdzz/PlaceableItems#37]
https://gist.github.com/NotAVerb/4eda92894172f5a454cf6d6ff4b50eff

Placeable Items causes a crash during preinitialization.

**Comment by JasonKillsUs** [comment]
Mc 1.12.2 _2631: same crash here with "placeableitems-3.3.jar"

**Comment by Ferdzz** [comment]
Oh no that's not good.. I'll be looking at this ASAP after work. Sorry for the inconveniences

**Comment by ProsperCraft** [comment]
ME too - https://gist.github.com/ProsperCraft/fab0a057c1456d892061cec250bd4773

Looks like its compiled against the wrong version of Minecraft perhaps?

**Comment by ProsperCraft** [comment]
Its confusion to release another of the same version, I recommend ticking the version up every build you push to curse to avoid confusion.

Still crashes https://gist.github.com/ProsperCraft/c3dd13a15f9358add895dad75c1b8d9f

**Comment by Ferdzz** [comment]
I have the same Forge & PI version as you but it doesn't crash on my end. What a bother. The crash log tells me there's a version mismatch somewhere but I fail to understand where.

**Comment by NotAVerb** [comment]
I just tested the new 3.3 build. It seems to be working fine on my end.

**Comment by Ferdzz** [comment]
Thanks for the report @NotAVerb . @ProsperCraft can you double check you're using the right version I uploaded today?

**Comment by ProsperCraft** [comment]
Worked after I manually updated again.

Again...version numbers :)

**Comment by Ferdzz** [comment]
Thanks for the quick answer everyone, apologies for the mistake. Not sure what happened but looks like the first build was wrong somehow.

If you're still having problems running the mod please open a new issue
