### ISSUE TITLE
[Suggestion] updated model for 3 items

### ISSUE THREAD

**Issue by RyanCR03** [Ferdzz/PlaceableItems#46]
the diamond and the emerald look like it was taken straight from faithful 32x i think it doesnt fit with minecraft.
also the enchanted book is using the old book model for the book, the enchanted book's pages look squished and again its 32x

**Comment by Ferdzz** [comment]
Could you include screenshots? It may be because you were using a texture pack. At some point there was a bug where it would use the textures from the texture pack, and not the ones we wanted. Might be a few problematic models left

**Comment by Ferdzz** [comment]
I'm closing this suggestion due to lack of activity. Please let us know if you want to reopen it
