### ISSUE TITLE
Placeable Arrow Breaking Causes Crash

### ISSUE THREAD

**Issue by WalkerNewton** [Ferdzz/PlaceableItems#48]
Hi there! I love placeable items but someone placed a tipped arrow and I think there's a glitch with another mod in the pack. It says the placed item is an "Uncraftable Tipped Arrow" and when someone tries to break it, they crash. When we try using a block breaker, (such as the mechanical miner from Extra Utilities), it crashes the entire server, and then whenever we log in to that area, it just does a crash loop. Below is the client log - and a screenshot of what the item looks like in-game. 

Client Log: [Paste Link](https://paste.ee/p/scbAP)
![2019-05-21_23 46 08](https://user-images.githubusercontent.com/37993138/58146180-03be1800-7c23-11e9-9b70-dbfae7944682.png)

**Comment by JSBOfficial** [comment]
I think it needs to increase the substring from 10 to something higher in BlockArrow.class at line 62? This is just my guess from the log submitted.

**Comment by BinarSkugga** [comment]
Log link is broken.

**Comment by Ferdzz** [comment]
Closing because log has expired and this bug was reported for a version that is no longer supported
