### ISSUE TITLE
Interaction with mccreery/better-hud causes game to crash

### ISSUE THREAD

**Issue by BestMordaEver** [Ferdzz/PlaceableItems#49]
Better HUD (or BHUD) provides configurable HUD, that can be disabled completely in it's internal menu.
The game crashes after you pick up enchanted sword with BHUD enabled. Specifically, several seconds after you break the sword block (which doesn't drop the sword) the game freezes and crashes. It consistently happens with BHUD enabled and inconsistently with BHUD being disabled, but present.
Yes, it works perfectly without BHUD. I already posted the issue to mccreery
[latest.log](https://github.com/mccreery/better-hud/files/3363504/latest.log)
[crash-2019-07-05_19.37.46-server.txt](https://github.com/mccreery/better-hud/files/3363506/crash-2019-07-05_19.37.46-server.txt)

**Comment by Ferdzz** [comment]
Hard to tell what's the cause from these logs

**Comment by BestMordaEver** [comment]
McCreary: See the option to disable NBT storage in the block viewer. That functionality will be removed from the next version because of this and many similar crashes.
