### ISSUE TITLE
Make a configuration to allow for disabling certain items

### ISSUE THREAD

**Issue by Ferdzz** [Ferdzz/PlaceableItems#52]
[Suggested by Kutze on CurseForge](https://www.curseforge.com/minecraft/mc-mods/placeable-items#c369)

> Can you add a config to allow you to disable and enable certain items to be placed as models, because Quark has a feature where you can place a Blaze Rod, and it also places one from this mod

**Comment by supersaiyansubtlety** [comment]
I would also appreciate this feature on 1.12. 
It can be pretty annoying trying to use a lava/water bucket against a block with an inventory. I also frequently accidentally place my sword. 
Another approach that could help with these issues it to allow configuration of the key you hold to be able to place items. 
So you could, for example, hold P+right-click to place a placeable item.

**Comment by Ferdzz** [comment]
Closing because this is no longer relevant after the implementation of #13

**Comment by xJon** [comment]
This is still relevant for 1.12, would be great if the mod offered this option to resolve the conflict with Quark.
