### ISSUE TITLE
Dupe glitch

### ISSUE THREAD

**Issue by BtChunkie** [Ferdzz/PlaceableItems#53]
Hello, I just want to report that there is a dupe glitch where if you quickly place and then take back a sword (any sword) it duplicates it (even with the same enchantments etc). Doesn't work with any other items though. (If needed I can record the bug)

**Comment by BtChunkie** [comment]
Mod version : placeableitems-3.3
Forge : 1.12.2-14.23.5.2838
MC version : 1.12.2

Video  : https://youtu.be/UYggJb4Z8u4
Basically all you have to do is keep spamming to place and break the sword and it will duplicate.

**Comment by Ferdzz** [comment]
That's odd, thanks for the video

**Comment by BtChunkie** [comment]
My mistake, I think that I've found out the problem. I think it's a thing with the mod "CarryOn" which allows you to take things into your hands (like animals and chests) for easy transport.

**Comment by BtChunkie** [comment]
I put : "placeableitems:*" into the blacklist of carryon.cfg and it fixed everything, sorry for wasting your time, this was totally my fault :(

**Comment by BinarSkugga** [comment]
Closing since its a problem from CarryOn

**Comment by Ferdzz** [comment]
@BtChunkie Thanks for sharing the fix with us, we'll include it in a list of common issues where people can find fixes for their issues with other mods or with the installation

**Comment by BinarSkugga** [comment]
@BtChunkie seems like a hotfix was done in 2018. Are you using the latest version of CarryOn ? Tschipp/CarryOn#102
