### ISSUE TITLE
[Suggest] Set tile-entities to don't being ticked

### ISSUE THREAD

**Issue by andry08** [Ferdzz/PlaceableItems#6]
I suggest you to add this to all the tile entity of items:
```@Override
public boolean canUpdate() {
	return false;
}
```
This will make the tiles to don't being ticked and will optimize the performace (in part).
P.S. sorry for my bad english

**Comment by Ferdzz** [comment]
That's a great idea! I was not aware this was a feature and I'll commit this shortly
I do know that performance-wise, ISBRH's are better, but I'm not quite sure how to handle them or if they will fit our needs completely.

**Comment by andry08** [comment]
sorry if i write when it's already closed but i wantt o say that this will optimize performace when there are are a lot of placeable items in the same chunk. when there are 10-20 placed items there is only a minimal difference of performance

**Comment by Ferdzz** [comment]
Where you talking about the canUpdate or the ISBRH's? Otherwise no problem in commenting a closed issue :smile:

**Comment by andry08** [comment]
yes i was talking abot the canUpdate :smile:
