### ISSUE TITLE
Support 1.15

### ISSUE THREAD

**Issue by Ferdzz** [Ferdzz/PlaceableItems#71]
Update & move to support Minecraft 1.15.x, when [Forge is available](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.15.2.html) in recommended

**Comment by 2008Choco** [comment]
Due to changes with the rendering system, Forge's fluid tile entity renderer may need a little loving. That aside, the update process shouldn't be all that difficult 😄

**Comment by Ferdzz** [comment]
Forge 1.15.2 now has a recommended version 31.1.0. Will need some time to look at it and make sure it's ready to port

**Comment by Ferdzz** [comment]
Done as of v4.2
