### ISSUE TITLE
1.15.2 When items are placed they disappear?

### ISSUE THREAD

**Issue by chyper111** [Ferdzz/PlaceableItems#84]
**Describe the bug**
We tried to place several items from your selection and the just disappeared. they seemed to place for a sec and the just vanished.  Where playing lan mod latest update for 1.15 but it was having the problem before the update so i dont really know anything more to try or do about it. thanks for any help you can offer.

 **To Reproduce**
3. ...

 **Expected behavior**
A clear and concise description of what you expected to happen, if applicable.

 **Screenshots**
If applicable, add screenshots to help explain your problem. If a video is more relevant, feel free to post one here too

 **Versions (please complete the following information):**
 - Minecraft version: 1.15.2
 - PlaceableItems version: 4.2
 - Forge version:31.2.36

**Comment by Ferdzz** [comment]
Thanks for your report. I was able to reproduce this issue, but only as the secondary player when playing on LAN servers. I'll try to find where this issue comes from
