### ISSUE TITLE
[1.15.2] Release 4.2.1 is not tagged as a Forge mod on CurseForge.

### ISSUE THREAD

**Issue by Vaelzan** [Ferdzz/PlaceableItems#85]
(Not following the normal issue format since this is an issue with the tags for the mod on CurseForge, not a bug in the mod itself.)

The 4.2.1 release is not tagged as a Forge mod when you uploaded it to CurseForge, which causes GDLauncher to think it is a Fabric-only release and therefore not available to download inside the launcher (which hides Fabric-only mods in Forge instances).

**Comment by Ferdzz** [comment]
Thank you for the heads up! I updated the file on CurseForge
