### ISSUE TITLE
Enable Gravity on Placeable Item Blocks

### ISSUE THREAD

**Issue by JSBOfficial** [Ferdzz/PlaceableItems#87]
**Is your feature request related to a problem? Please describe.**
Placeable Item Blocks tends to float when destroying the bottom block it is placed on.

**Describe the solution you'd like**
Just add fall physics to it same as vanilla anvil block but it should only be enabled for some blocks.

**Describe alternatives you've considered**
Destroy Placeable Item Block when bottom block is destroyed.

**Comment by Ferdzz** [comment]
This was a feature in previous versions, but I felt like it was only a limiter to creativity. It did not add useful gameplay elements and therefore we won't bring it back.
Thank you for the suggestion though!
