### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Mattabase** [Ferdzz/PlaceableItems#9]
I can not seem to find the config for this mod.

**Comment by Ferdzz** [comment]
There is currently no configuration available in this mod.

If you have specific configs you'd like implemented please do tell me!

**Comment by Mattabase** [comment]
In this case I have an issue, I have mod that makes the blaze rod doing something on shift right click on a block with you mod however it just places the Rod.

**Comment by Ferdzz** [comment]
Alright, I'll see what I can do. Would you mind telling me what the mod is?

**Comment by Mattabase** [comment]
Vanilla Magic is the name of the mod. It uses the Blaze rod as a "wand"

**Comment by Ferdzz** [comment]
I don't think making the entire config framework is worth it for just this issue. I'm thinking of disabling the blaze rod placement if that particular mod is loaded, does that sound okay?

**Comment by Mattabase** [comment]
Yeah, that would be great. Thank you.

**Comment by Ferdzz** [comment]
Perfect, I'll include this in the next release, which should be published in under a week.

**Comment by xJon** [comment]
Could you also implement this for the Quark mod?
