### ISSUE TITLE
[1.15.2-4.2.1] Players can place items while in spectator mode.

### ISSUE THREAD

**Issue by Vaelzan** [Ferdzz/PlaceableItems#96]
**Describe the bug**
Items can be placed while the player is in spectator mode, if the player had previously selected them on the hotbar while in survival or creative mode.

 **To Reproduce**
Steps to reproduce the behaviour:
1. Select a placeable item in the hotbar.
2. Switch to Spectator Mode.
3. Shift-Right-Click Ground.

 **Expected behaviour**
Spectators should not be able to interact with the world in any way.

 **Screenshots**
N/A, description should be clear enough.

 **Versions (please complete the following information):**
 - Minecraft version: 1.15.2
 - PlaceableItems version: 4.2.1
 - Forge version: 31.2.41

**Comment by Ferdzz** [comment]
Thank you for the report, I'll be fixing this ASAP

**Comment by Ferdzz** [comment]
Fixed in 00a44ee635875879f557e1b34a7d2de810584eea
