### ISSUE TITLE
Config for placement of buckets

### ISSUE THREAD

**Issue by joonas-erho** [Ferdzz/PlaceableItems#99]
Hello, I was wondering if you could add a configuration option for buckets?

Right now, if you shift-right click water or lava with a bucket, the bucket is placed down on the block as a placeable item, and the liquid is not collected. This is, of course, intended behaviour, but it could be made so that if a config setting is enabled, shift-right clicking liquids will still pick them up instead of placing down the bucket.

**Comment by Ferdzz** [comment]
That was not an easy fix to find! Thanks for bringing this to my attention, it will be fixed in the next version.

Instead of going through the configuration, it just always checks if you're using the bucket on something that should be a picked up fluid
